name: cuda_build
channels:
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.15.3
  - binutils_impl_linux-64=2.45
  - binutils_linux-64=2.45
  - bzip2=1.0.8
  - cuda-cccl_linux-64=13.1.115
  - cuda-command-line-tools=13.1.1
  - cuda-compiler=13.1.1
  - cuda-crt-dev_linux-64=13.1.115
  - cuda-crt-tools=13.1.115
  - cuda-ctadvisor=13.1.115
  - cuda-cudart=13.1.80
  - cuda-cudart-dev=13.1.80
  - cuda-cudart-dev_linux-64=13.1.80
  - cuda-cudart-static=13.1.80
  - cuda-cudart-static_linux-64=13.1.80
  - cuda-cudart_linux-64=13.1.80
  - cuda-cuobjdump=13.1.115
  - cuda-cupti=13.1.115
  - cuda-cupti-dev=13.1.115
  - cuda-cuxxfilt=13.1.115
  - cuda-driver-dev=13.1.80
  - cuda-driver-dev_linux-64=13.1.80
  - cuda-gdb=13.1.115
  - cuda-libraries=13.1.1
  - cuda-libraries-dev=13.1.1
  - cuda-nsight=13.1.115
  - cuda-nvcc=13.1.115
  - cuda-nvcc-dev_linux-64=13.1.115
  - cuda-nvcc-impl=13.1.115
  - cuda-nvcc-tools=13.1.115
  - cuda-nvcc_linux-64=13.1.115
  - cuda-nvdisasm=13.1.115
  - cuda-nvml-dev=13.1.115
  - cuda-nvprune=13.1.115
  - cuda-nvrtc=13.1.115
  - cuda-nvrtc-dev=13.1.115
  - cuda-nvtx=13.1.115
  - cuda-nvvm-dev_linux-64=13.1.115
  - cuda-nvvm-impl=13.1.115
  - cuda-nvvm-tools=13.1.115
  - cuda-opencl=13.1.115
  - cuda-opencl-dev=13.1.115
  - cuda-profiler-api=13.1.115
  - cuda-sanitizer-api=13.1.118
  - cuda-tileiras=13.1.80
  - cuda-toolkit=13.1.1
  - cuda-tools=13.1.1
  - cuda-version=13.1
  - cuda-visual-tools=13.1.1
  - dbus=1.16.2
  - fontconfig=2.15.0
  - freetype=2.14.1
  - gcc_impl_linux-64=15.2.0
  - gcc_linux-64=15.2.0
  - gds-tools=1.16.1.26
  - gmp=6.3.0
  - gxx_impl_linux-64=15.2.0
  - gxx_linux-64=15.2.0
  - icu=78.2
  - kernel-headers_linux-64=6.12.0
  - ld_impl_linux-64=2.45
  - libcublas=13.2.1.1
  - libcublas-dev=13.2.1.1
  - libcufft=12.1.0.78
  - libcufft-dev=12.1.0.78
  - libcufile=1.16.1.26
  - libcufile-dev=1.16.1.26
  - libcurand=10.4.1.81
  - libcurand-dev=10.4.1.81
  - libcusolver=12.0.9.81
  - libcusolver-dev=12.0.9.81
  - libcusparse=12.7.3.1
  - libcusparse-dev=12.7.3.1
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-devel_linux-64=15.2.0
  - libgcc-ng=15.2.0
  - libglib=2.86.3
  - libglvnd=1.7.0
  - libgomp=15.2.0
  - libiconv=1.18
  - liblzma=5.8.2
  - libnpp=13.0.3.3
  - libnpp-dev=13.0.3.3
  - libnvfatbin=13.1.115
  - libnvfatbin-dev=13.1.115
  - libnvjitlink=13.1.115
  - libnvjitlink-dev=13.1.115
  - libnvjpeg=13.0.3.75
  - libnvjpeg-dev=13.0.3.75
  - libnvptxcompiler-dev=13.1.115
  - libnvptxcompiler-dev_linux-64=13.1.115
  - libopengl=1.7.0
  - libpng=1.6.54
  - libsanitizer=15.2.0
  - libsqlite=3.51.2
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.41.3
  - libxcb=1.17.0
  - libxkbcommon=1.13.1
  - libxkbfile=1.1.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - nsight-compute=2025.4.1.2
  - nspr=4.38
  - nss=3.118
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - pcre2=10.47
  - pthread-stubs=0.4
  - sysroot_linux-64=2.39
  - tzdata=2025c
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.6
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.7
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.5
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - zstd=1.5.7
prefix: /mnt/aigc/users/qianjianheng/miniconda3/envs/cuda_build
